import requests
import json

EXAMPLES = {
    "DNA Polymerase (EC2)": "MFSKLLILNKNKFACLVFLFITMILSHIPFFPFKKPSHPRHQMYTSIPQIPTTKSYIPHNRNVHVQFTHKIIKAKLQHNIQKQYRFYFQKHRRVKSEIQHLKEKWQFYLDIHPGNGKIVIHYLSDKIPEFHLLKKKIIVTEKGYERPSKRVQNKRNKDSFVYHYHLNTKKHPFYIKVKNGKIVLTKKASGKIIDLIVNQKIPEFHLKKKIIITEQDYEFPNKPLQNKRKKDSFVYHYHLNTKKHPFYIKVKNGKIVLTKKASGKIIDLIVNQGIPEFHLKKKIIITEQDYEFPNKPLQNKRKKDSFVYHYHLNTKKHPFYIKVRNGK",
    
    "Lipase (EC3)": "MKKLLPLLCAGLLLAACSFGQGEAGGITSWYNMHVGMTSRSLKGKITDLMGYTVHLKNPSLFDIQVQNLLDKYKSGDKHPLSYIKRVEHSFHGISEDLVNFNGKVFLDVPLMQIDVVKANQASNPLVEFHIGNGNGTVDFTPANTANQVNQLWQDNTNVSQYFYSNGADYLAQSASIPVHSQPIDGLVAVRAGTTKVVKAIDANQNPNPATVSYIRNVGSFFADYKVSQEKNMLQFRFGFYPKPLSDQEQFTFDFGRNAFSAFDAAKHQDTYKEMLSKYIAEGGRDQIQALDRLEKHKTLSTYSYGMNGDHFISQELAVSAQTLTKKSVFVQKDFTFDLKNKGVIFSHEQFKPVVVVRKEGKDPRAAKTITKMVESAYGIMNSFIEQGLIGTGQGTPANAILFSTYGFEDAIIAYQGKGCPVIWVGFAGGNTPYVLIDLNGFSAVGMTKVSSVEAMDAIRQALNMVRLKE",
    
    "Short Kinase": "MEAIAKYDFKATADDELSFKRGDILKVLNEECDQNWYKAELNGKDGFIPKNYIEMKPHPWFFGQVDRKQDYHFLKQSVRGMLQARGFFKREGIILAVCDERGSMIYETPANFLPHELYGSGLQPNVPGMGPFWPMVKIWFKDLKSKQARMSQREKLFVAEGQTKPPESQKLVSGVLFQPNGGLDKAGIGLSPEQAVRYLMKCLGLNPVALEGIDTTYLSPWKLPDRPSLTPESRDVQKLLPHKPFTLDYQKRQPRLLKASNLLSLLTEVDEAKKVLRQAMRNSVLTNLELGFQGTLRLAFDSRREAPSLRPPHPEQ",
    
    "Carbonic Anhydrase (EC4)": "MSHHWGYGKHNGPEHWHKDFPIAKGERQSPVDIDTHTAKYDPSLKPLSVSYDQATSLRILNNGHAFNVEFDDSQDKAVLKGGPLDGTYRLIQFHFHWGSLDGQGSEHTVDKKKYAAELHLVHWNTKYGDFGKAVQQPDGLAVLGIFLKVGSAKPGLQKVVDVLDSIKTKNQAVTVTDNAAKPSNVKDKKLFKPSSPPEEIGKQLLKVEKEPWDVERPGAGVLQGLIHGSGSASAGIPVFDNKDDPSSVEKIVNKTIENSFEAQKAANPCIPMRFTFDPKLFLQHSKQPINVNNGHAFNVEFDDSQDKAVLKGGPLDGTYRLIQFHFHWGSLDGQGSEHTVDKKKYAAELHLVHWNTKYGDFGKAVQQPDGLAVLGIFLKVGSAKPGLQKVVDVLDNIKN",
    
    "Minimal Length (50 AA)": "MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLS"
}

for name, sequence in EXAMPLES.items():
    print(f"\n{'='*70}")
    print(f"Testing: {name}")
    print(f"Length: {len(sequence)} AA")
    print(f"{'='*70}")
    
    response = requests.post(
        "http://localhost:8000/predict",
        json={"sequence": sequence}
    )
    
    result = response.json()
    
    print(f"🎯 Predicted: {result['predicted_class']}")
    print(f"📊 Confidence: {result['confidence']*100:.2f}%")
    print(f"⏱️  Time: {result['inference_time_ms']:.2f}ms")
    
    # Show top 3 probabilities
    print(f"\nTop 3 predictions:")
    sorted_probs = sorted(result['all_probabilities'].items(), key=lambda x: x[1], reverse=True)[:3]
    for cls, prob in sorted_probs:
        print(f"  {cls}: {prob*100:6.2f}%")